[theme]
base = "dark"
primaryColor = "#4CAF50"
backgroundColor = "#0e1117"  # almost black, subtle blue undertone
secondaryBackgroundColor = "#1c1f26"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true
